name: Testing
on: pull_request

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      run: 
          pip3 install --user -r requirements.txt && pytest src/v1/tests/si_test.py